/**
 * Well-known feat IDs for commonly-used feats.
 * These match the slugified IDs generated by the feat seeder.
 */

/** Toughness - grants +3 HP, +1 per level beyond 3rd */
export const FEAT_TOUGHNESS = "feat-toughness";

/** Dodge - grants +1 AC */
export const FEAT_DODGE = "feat-dodge";

/** Combat Expertise - stance that trades attack for AC */
export const FEAT_COMBAT_EXPERTISE = "feat-combat-expertise";

/** Power Attack - stance that trades attack for melee damage */
export const FEAT_POWER_ATTACK = "feat-power-attack";

/** Deadly Aim - stance that trades attack for ranged damage */
export const FEAT_DEADLY_AIM = "feat-deadly-aim";

/** Two-Weapon Fighting - allows dual wielding weapons */
export const FEAT_TWO_WEAPON_FIGHTING = "feat-two-weapon-fighting";
