/**
 * Feat seeder that imports static feat data and inserts into the database.
 * Uses pre-parsed data from featData.ts generated by scripts/generateFeatData.ts.
 */

import { randomUUID } from "crypto";
import type { BetterSQLite3Database } from "drizzle-orm/better-sqlite3";
import * as schema from "../schema.js";
import { FEAT_DATA } from "./featData.js";

/**
 * Effect types for the 6 starter feats.
 * These override the auto-generated effectType values from the CSV.
 */
const STARTER_FEAT_EFFECTS: Record<string, string> = {
  Toughness: "hp_bonus",
  Dodge: "ac_bonus",
  "Combat Expertise": "combat_stance",
  "Power Attack": "combat_stance",
  "Deadly Aim": "combat_stance",
  "Two-Weapon Fighting": "equipment_unlock",
};

/**
 * Seed all feats from the pre-parsed feat data into the database.
 * Inserts feats into the feats table and their prerequisites into feat_prerequisites.
 * Uses onConflictDoNothing to allow re-running without errors.
 *
 * @param db - Drizzle database instance
 * @returns Object with counts of feats and prerequisites seeded
 */
export async function seedFeats(
  db: BetterSQLite3Database<typeof schema>,
): Promise<{ featsSeeded: number; prerequisitesSeeded: number }> {
  console.log("Creating feats...");

  let featsSeeded = 0;
  let prerequisitesSeeded = 0;

  for (const feat of FEAT_DATA) {
    const featId = `feat-${slugify(feat.name)}`;

    // Insert the feat, using starter feat effect type if applicable
    const effectType = STARTER_FEAT_EFFECTS[feat.name] ?? feat.effectType;

    await db
      .insert(schema.feats)
      .values({
        id: featId,
        name: feat.name,
        prerequisitesText: feat.prerequisitesText,
        shortDescription: feat.shortDescription,
        longDescription: feat.longDescription,
        sourceBook: feat.sourceBook,
        category: feat.category,
        effectType,
        supportabilityStatus: feat.supportabilityStatus,
      })
      .onConflictDoNothing();

    featsSeeded++;

    // Insert prerequisites
    for (const prereq of feat.prerequisites) {
      await db
        .insert(schema.featPrerequisites)
        .values({
          id: randomUUID(),
          featId,
          prerequisiteType: prereq.type,
          prerequisiteKey: prereq.key,
          prerequisiteValue: prereq.value,
        })
        .onConflictDoNothing();

      prerequisitesSeeded++;
    }
  }

  console.log(
    `  ✓ Created ${featsSeeded} feats with ${prerequisitesSeeded} prerequisites\n`,
  );

  return { featsSeeded, prerequisitesSeeded };
}

/**
 * Convert a feat name to a URL-safe slug for use as an ID.
 * @param name - Feat name to slugify
 * @returns Lowercase slug with spaces and special chars replaced by hyphens
 */
function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
